### ISSUE TITLE
video_result

### ISSUE THREAD

**Issue by frozoul** [frozoul/4K-NeRF#1]
https://user-images.githubusercontent.com/15401551/206893466-7bb285f7-67e4-42b5-9fa9-d3e9e784c197.mp4

https://user-images.githubusercontent.com/15401551/206893643-a4c09b2b-fb7b-4af9-aa4c-8acf006f4e07.mp4

**Comment by kwea123** [comment]
do you have all 8 scenes in llff? I only see 4 in the repo
