### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Richardych** [frozoul/4K-NeRF#6]
Hi, 

I find that this code (https://github.com/frozoul/4K-NeRF/blob/a8fdc8e98b/run_sr.py#L829) in run_sr.py will cause a out of bounds error:

target_4x = rgb_srgt_train[sel_b, sel_r_4x, sel_c_4x, :]

**Comment by xyIsHere** [comment]
I encountered the same problem. Could you share with me the solution?

**Comment by ztqwerty** [comment]
> Hi,
> 
> I find that this code (https://github.com/frozoul/4K-NeRF/blob/a8fdc8e98b/run_sr.py#L829) in run_sr.py will cause a out of bounds error:
> 
> target_4x = rgb_srgt_train[sel_b, sel_r_4x, sel_c_4x, :]

I encountered the same issue. How did you solve it eventually?
